server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediasoft-test-task
    username: postgres
    password: ${PWD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  app:
    kafka:
      enabled: true

  kafka:
    bootstrapAddress: localhost:9092
    groupId: group1