server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediasoft-test-task
    username: postgres
    password: ${PWD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

account-service:
  host: http://localhost:8081
  methods:
    get-account: /account

crm-service:
  host: http://localhost:8081
  methods:
    get-inn: /inn

orchestrator-service:
  host: http://localhost:8080
  methods:
    process-start: /process/start

app:
  kafka:
    enabled: false
aws:
  path: chromedriver
  accessKeyId: ${accessKeyId}
  secretAccessKey: ${secretAccessKey}
  region: ${region}
  bucket: ${bucket}

kafka:
  bootstrapAddress: localhost:9092
  groupId: group1