spring:
  datasource:
    username: sa
    password: ${PWD}
    url: jdbc:h2:mem:test;LOCK_TIMEOUT=60000
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

    #liquibase:
    #change-log: classpath:db/changelog/changelog.xml
    #enabled: false

  h2:
    console:
      enabled: true #http://localhost:8080/h2-console

app:
  scheduling:
    enabled: true
    period: 120000
    priceIncreasePercentage: 10
    optimization: true

currency-service:
  host: http://localhost:8070
  methods:
    get-currency: /currency
